version: "3.9"
services:
  productservice:
    container_name: ProductServiceApp
    command: java -jar target/demo-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - mongo_db
      - redis_server
    networks:
      - warehouse_common_network
  mongo_db:
    container_name: mongodb_productservice
    image: 'mongo:4.4.3'
    restart: always
    ports:
      - 27018:27017
    networks:
      - warehouse_common_network
  redis_server:
    container_name: redis_productservice
    image: 'redis:7.0.4'
    restart: always
    ports:
      - 16379:6379
    networks:
      - warehouse_common_network
networks:
  warehouse_common_network:
    external: true
