version: "3.9"
services:
  productservice:
    container_name: ProductServiceApp
    command: java -jar target/demo-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mongoDB
      - redisCache
    networks:
      - warehouse_commonNetwork
    environment:
      - spring.rabbitm.host=rabbitmq
  mongoDB:
    container_name: mongoDBProductService
    image: 'mongo:4.4.3'
    restart: always
    ports:
      - "27018:27017"
    networks:
      - warehouse_commonNetwork
  redisCache:
    container_name: redisCacheProductService
    image: 'redis:7.0.4'
    restart: always
    ports:
      - "16379:6379"
    networks:
      - warehouse_commonNetwork
networks:
  warehouse_commonNetwork:
    external: true
